import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import Navbar from "./content/Navbar";
import ProductClient from "./content/productClient";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
 
      <body >
        <ProductClient>
          <ThemeProvider attribute='class' defaultTheme="system" enableSystem>
            <Navbar />
            <main className=" mx-auto w-full px-4 sm:px-12 lg:px-16">
              {children}
            </main>
          </ThemeProvider>
        </ProductClient>
      </body>
    </html>
  );
}
